kraken:
  api_key: "<Put your API key here>"
  api_secret: "<Put your API secret here>"

binance:
  api_key: "<Put your API key here>"
  api_secret: "<Put your API secret here>"

aws:
  api_key: "<Put your API key here>"
  api_secret: "<Put your API secret here>"

backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_balance: 10000
