# config/config.example.yaml

kraken:
  api_key: "mXn+WT18e9Swo0st6/Yt1alPcLuu/jVWaBl21qqIZdMGQTpEi2l0rlNz"
  api_secret: "n15puHpUIsctLTPH9KR7FZjW+DUt7+KfEKIAFTzGpTou4DOBxRPRaPoCudNvQ9il/9zECalUxYiix0PPKUYfnw=="
  default_pair: "XBTUSD"

binance:
  api_key: "<Put your API key here>"
  api_secret: "<Put your API secret here>"
  default_pair: "BTCUSDT"

trade:
  base_asset: "BTC"
  quote_asset: "USD"
  interval: "1h"
  order_size: 0.001
  slippage: 0.01
  paper_trading: true  

strategy:
  name: "sma"
  parameters:
    short_window: 20
    long_window: 50

backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_balance: 10000
